### ISSUE TITLE
NullPointerException at JDBCUtils.Close(JDBCUtils.java:181)

### ISSUE THREAD

**Issue by hginzel** [atris/JDBC_FDW#21]
I am testing jdbc_fdw against [Teradata](http://terahelp.blogspot.cz/2009/08/connecting-to-database-using-teradata.html) 14.10

```
CREATE EXTENSION IF NOT EXISTS jdbc_fdw;
DROP SERVER IF EXISTS TD_Dev CASCADE;
CREATE SERVER TD_Dev FOREIGN DATA WRAPPER jdbc_fdw OPTIONS (
drivername  'com.teradata.jdbc.TeraDriver',
url     'jdbc:teradata://host/database=foo',     -- ,tmode=ANSI,charset=LATIN1250_1A0
jarfile '/opt/Teradata/jdbc/terajdbc4.jar'
-- querytimeout '35',
-- maxheapsize  '600'
);
CREATE USER MAPPING FOR CURRENT_USER SERVER TD_Dev
OPTIONS (username 'foo', password 'bar');
CREATE FOREIGN TABLE Test_td1 (Id int, Code text) SERVER TD_Dev
OPTIONS (QUERY 'SELECT * FROM foo.test1');
SELECT * FROM Test_td1;
```

with result

```
…
CREATE FOREIGN TABLE
psql:test_TD_fdw.sql:26: ERROR:  java.lang.NullPointerException
        at JDBCUtils.Close(JDBCUtils.java:181)
```

PostgreSQL 9.4. How can I solve this, please?

**Comment by pafiti** [comment]
Hi ginzel,

I get exactly the same issue trying to get access to Phoenix server with jdbc_fdw and PostgreSQL 9.5.
Have you been able to solve this issue ?

Thanks

**Comment by ftzdomino** [comment]
Here's my workaround:
https://github.com/atris/JDBC_FDW/pull/32

**Comment by atris** [comment]
Fixed
